### PR TITLE
HTTP 500 raised by POST /shares API when failing to handle share_type…

### PR DESCRIPTION
**Pull request by Jipheens**
… in request

### CODE REVIEW

**Comment by Jipheens** [comment]
HTTP 500 raised by POST /shares API when failing to handle "share_type" in request

**Comment by Jipheens** [comment]
HTTP 500 raised by POST /shares API when failing to handle "share_type" in request with unit test

**Comment by gouthampacha** [comment]
Hi @Jipheens 

this project does not accept code changes via GitHub pull requests; we use https://review.opendev.org - a gerrit instance to submit code. 

Some resources for your reference:

https://docs.opendev.org/opendev/infra-manual/latest/developers.html#quick-reference
https://docs.openstack.org/manila/latest/contributor/contributing.html

**Comment by Jipheens** [comment]
okay let me check on that. thankyou

**Comment by openstack-mirroring** [comment]
Thank you for your contribution!

This GitHub repository is just a mirror of https://opendev.org/openstack/manila, where development really happens. Pull requests proposed on GitHub are automatically closed.

If you are interested in pushing this code upstream, please note that OpenStack development uses Gerrit for change proposal and code review.

If you have never contributed to OpenStack before, please see:
https://docs.openstack.org/contributors/code-and-documentation/quick-start.html

Feel free to reach out to the First Contact SIG by sending an email to the openstack-discuss list with the tag '[First Contact]' in the subject line. To email the mailing list, you must first subscribe which can be done here:
http://lists.openstack.org/cgi-bin/mailman/listinfo/openstack-discuss

**Comment by Jipheens** [comment]
[image: image.png]

**Comment by Jipheens** [comment]
i am stuck trying to push my code

**Comment by Jipheens** [comment]
i finally managed to push my changes to   Gerrit. i now just need you to
help me identify the link that i am supposed to paste on my outreachy
account for my final application. thankyou.

**Pull request closed without merging**
